### DISCUSSION TITLE
Help converting cloudformation yaml to terraform

### DISCUSSION THREAD

**Discussion by d-saravanan** [DontShaveTheYak/cf2tf#136] [Q&A]
Hi,
I tried to convert the attached cloudformation yaml file to terraform to provision a new terraform cloudwatch alarm, however could not get it to convert. Can you please help me with this.

Attached is the yaml file for reference. If you can point out something missing, it will be helpful for me to add and fix.

yaml file
```
Type: AWS::CloudWatch::Alarm
Properties:
    AlarmName: test
    ActionsEnabled: true
    OKActions: []
    AlarmActions:
        - arn:aws:sns:us-west-1:672714205403:saravanan.doraiswamy@gmail.com
    InsufficientDataActions: []
    Dimensions: []
    EvaluationPeriods: 1
    DatapointsToAlarm: 1
    Threshold: 10000
    ComparisonOperator: GreaterThanThreshold
    TreatMissingData: missing
    Metrics:
        - Id: e1
          Label: read latency
          ReturnData: true
          Expression: ( m1/m2)*1000
        - Id: m1
          Label: "Average write time, all volumes [sum: ${SUM}]"
          ReturnData: false
          Expression: |-
              SELECT SUM(VolumeTotalWriteTime)
              FROM SCHEMA("AWS/EBS", VolumeId)
          Period: 300
        - Id: m2
          ReturnData: false
          MetricStat:
              Metric:
                  Namespace: AWS/EBS
                  MetricName: VolumeReadOps
                  Dimensions:
                      - Name: VolumeId
                        Value: vol-0ab4207e19ebfcdee
              Period: 300
              Stat: Sum
```
