### ISSUE TITLE
Unable to convert cf2tf

### ISSUE THREAD

**Issue by premsgr6** [DontShaveTheYak/cf2tf#138]
its not converting cf to tf

 python3 --version
Python 3.8.10

$ cf2tf my_template.yaml > main.tf
// Converting my_template.yaml to Terraform!
~$ cat main.tf
 existing repo found.

**Comment by Breina** [comment]
Same for me.. Debug output:

```
cf2tf -v DEBUG alarm.yaml
// Converting alarm.yaml to Terraform!
debug: // Template location is alarm.yaml
 existing repo found.
debug: Ignoring section Parameters not found in ['Parameters', 'Mappings', 'Conditions', 'Resources', 'Outputs']
debug: Ignoring section Mappings not found in ['Parameters', 'Mappings', 'Conditions', 'Resources', 'Outputs']
debug: Ignoring section Conditions not found in ['Parameters', 'Mappings', 'Conditions', 'Resources', 'Outputs']
debug: Ignoring section Resources not found in ['Parameters', 'Mappings', 'Conditions', 'Resources', 'Outputs']
debug: Ignoring section Outputs not found in ['Parameters', 'Mappings', 'Conditions', 'Resources', 'Outputs']
debug: Parsed the following resources for processing:
debug: {}
```

Contents of `alarm.yaml`:

```
Type: AWS::CloudWatch::Alarm
Properties:
    AlarmName: SomeAlarmName
    AlarmDescription: SomeAlarmDescription
    ActionsEnabled: true
    OKActions: []
    AlarmActions: []
    InsufficientDataActions: []
    Dimensions: []
    EvaluationPeriods: 1
    DatapointsToAlarm: 1
    Threshold: 10
    ComparisonOperator: GreaterThanThreshold
    TreatMissingData: missing
    Metrics:
        - Id: e1
          Label: SomeLabel
          ReturnData: true
          Expression: m2-m1
        - Id: m2
          ReturnData: false
          MetricStat:
              Metric:
                  Namespace: ContainerInsights/Prometheus
                  MetricName: some_metric
                  Dimensions:
                      - Name: controller
                        Value: qwe
                      - Name: service_name
                        Value: qwe
                      - Name: namespace
                        Value: qwe
                      - Name: channel
                        Value: qwe
                      - Name: ClusterName
                        Value: qwe
              Period: 300
              Stat: Maximum
        - Id: m1
          ReturnData: false
          MetricStat:
              Metric:
                  Namespace: ContainerInsights/Prometheus
                  MetricName: some_metric
                  Dimensions:
                      - Name: controller
                        Value: qwe
                      - Name: service_name
                        Value: qwe
                      - Name: namespace
                        Value: qwe
                      - Name: channel
                        Value: qwe
                      - Name: ClusterName
                        Value: qwe
              Period: 300
              Stat: Maximum
```

**Comment by shadycuz** [comment]
@Breina Your template is not valid cloudformation. You need to add a resources section and a Logical ID for your resource. Try this:

```yaml
Resources:
  MyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: SomeAlarmName
      AlarmDescription: SomeAlarmDescription
      ActionsEnabled: true
      OKActions: []
      AlarmActions: []
      InsufficientDataActions: []
      Dimensions: []
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: missing
      Metrics:
          - Id: e1
            Label: SomeLabel
            ReturnData: true
            Expression: m2-m1
          - Id: m2
            ReturnData: false
            MetricStat:
                Metric:
                    Namespace: ContainerInsights/Prometheus
                    MetricName: some_metric
                    Dimensions:
                        - Name: controller
                          Value: qwe
                        - Name: service_name
                          Value: qwe
                        - Name: namespace
                          Value: qwe
                        - Name: channel
                          Value: qwe
                        - Name: ClusterName
                          Value: qwe
                Period: 300
                Stat: Maximum
          - Id: m1
            ReturnData: false
            MetricStat:
                Metric:
                    Namespace: ContainerInsights/Prometheus
                    MetricName: some_metric
                    Dimensions:
                        - Name: controller
                          Value: qwe
                        - Name: service_name
                          Value: qwe
                        - Name: namespace
                          Value: qwe
                        - Name: channel
                          Value: qwe
                        - Name: ClusterName
                          Value: qwe
                Period: 300
                Stat: Maximum
```
