### ISSUE TITLE
Tag conversion issue

### ISSUE THREAD

**Issue by robomnis** [DontShaveTheYak/cf2tf#62]
Super minor, but for resource tags need some slight tweak to make them generate in the right format. 

Input (CloudFormation):
```
      Tags:
        - Key: Network
          Value: Public
        - Key: Name
          Value: Production VPC
```

Output:
```
  tags = [{'Key': '"Network"', 'Value': '"Public"'}, {'Key': '"Name"', 'Value': '"Production VPC"'}]
```

Should be:
```
tags = {
    Network = "Public"
    Name = "Production VPC"
    }
```

Current output errors for tags on `terraform plan`:
```
╷
│ Error: Invalid character
│ 
│   on vpc.tf line 104, in resource "aws_vpc" "vpc":
│  104:   tags = [{'Key': '"Network"', 'Value': '"Public"'}, {'Key': '"Name"', 'Value': '"Production VPC"'}]
│ 
│ Single quotes are not valid. Use double quotes (") to enclose strings.
╵
```
